{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module Printchapel where

-- pretty-printer generated by the BNF converter

import Abschapel
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)



instance Print Iden where
  prt _ (Iden i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
   RProg stmts -> prPrec i 0 (concatD [prt 0 stmts])


instance Print Stmt where
  prt i e = case e of
   RAssign lexpr rexpr -> prPrec i 0 (concatD [prt 0 lexpr , doc (showString "=") , prt 0 rexpr])
   RDecVar stmtvar -> prPrec i 0 (concatD [prt 0 stmtvar])
   Cond stmtcondition -> prPrec i 0 (concatD [prt 0 stmtcondition])
   While stmtwhile -> prPrec i 0 (concatD [prt 0 stmtwhile])
   For stmtfor -> prPrec i 0 (concatD [prt 0 stmtfor])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print BasicType where
  prt i e = case e of
   RInt n -> prPrec i 0 (concatD [prt 0 n])
   RFloat d -> prPrec i 0 (concatD [prt 0 d])
   RChar c -> prPrec i 0 (concatD [prt 0 c])
   RString str -> prPrec i 0 (concatD [prt 0 str])
   RBoolean boolean -> prPrec i 0 (concatD [prt 0 boolean])


instance Print LExpr where
  prt i e = case e of
   RLExpr iden -> prPrec i 0 (concatD [prt 0 iden])


instance Print RExpr where
  prt i e = case e of
   RAdd rexpr0 rexpr -> prPrec i 0 (concatD [prt 0 rexpr0 , doc (showString "+") , prt 0 rexpr])
   RGre rexpr0 rexpr -> prPrec i 0 (concatD [prt 0 rexpr0 , doc (showString ">") , prt 0 rexpr])
   RDiv rexpr0 rexpr -> prPrec i 0 (concatD [prt 0 rexpr0 , doc (showString "/") , prt 0 rexpr])
   RComp rexpr0 rexpr -> prPrec i 0 (concatD [prt 0 rexpr0 , doc (showString "==") , prt 0 rexpr])
   RElem basictype -> prPrec i 0 (concatD [prt 0 basictype])
   LExprR lexpr -> prPrec i 0 (concatD [prt 0 lexpr])


instance Print StmtVar where
  prt i e = case e of
   RVarBlock blockvars -> prPrec i 0 (concatD [doc (showString "var") , prt 0 blockvars])


instance Print BlockVar where
  prt i e = case e of
   RBlockVar iden type' rexpr -> prPrec i 0 (concatD [prt 0 iden , doc (showString ":") , prt 0 type' , doc (showString "=") , prt 0 rexpr])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print StmtCondition where
  prt i e = case e of
   If1 rexpr stmt -> prPrec i 0 (concatD [doc (showString "if") , prt 0 rexpr , doc (showString "then") , prt 0 stmt])
   If2 rexpr stmts -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 rexpr , doc (showString ")") , doc (showString "{") , prt 0 stmts , doc (showString "}")])


instance Print StmtWhile where
  prt i e = case e of
   WhileDo rexpr stmt -> prPrec i 0 (concatD [doc (showString "while") , prt 0 rexpr , doc (showString "do") , prt 0 stmt])
   WhileDoS rexpr stmts -> prPrec i 0 (concatD [doc (showString "while") , prt 0 rexpr , doc (showString "{") , prt 0 stmts , doc (showString "}")])


instance Print StmtFor where
  prt i e = case e of
   SForDoBloc iden aggr stmts -> prPrec i 0 (concatD [doc (showString "for") , prt 0 iden , doc (showString "in") , prt 0 aggr , doc (showString "{") , prt 0 stmts , doc (showString "}")])


instance Print Aggr where
  prt i e = case e of
   ForAggr n0 n -> prPrec i 0 (concatD [prt 0 n0 , doc (showString "..") , prt 0 n])


instance Print Boolean where
  prt i e = case e of
   RTrue  -> prPrec i 0 (concatD [doc (showString "true")])
   RFalse  -> prPrec i 0 (concatD [doc (showString "false")])


instance Print Type where
  prt i e = case e of
   RTypeInt  -> prPrec i 0 (concatD [doc (showString "int")])
   RTypeFloat  -> prPrec i 0 (concatD [doc (showString "real")])
   RTypeChar  -> prPrec i 0 (concatD [doc (showString "char")])
   RTypeString  -> prPrec i 0 (concatD [doc (showString "string")])
   RTypeBool  -> prPrec i 0 (concatD [doc (showString "boolean")])



