module Abschapel where

-- Haskell module generated by the BNF converter


newtype Iden = Iden String deriving (Eq,Ord,Show)
data Program =
   RProg [Stmt]
  deriving (Eq,Ord,Show)

data Stmt =
   RAssign LExp RExp
 | RDecVar StmtVar
  deriving (Eq,Ord,Show)

data BasicType =
   RInt Integer
 | RFloat Double
 | RChar Char
 | RString String
 | RBoolean Boolean
  deriving (Eq,Ord,Show)

data LExp =
   RLExp Iden
  deriving (Eq,Ord,Show)

data RExp =
   RAdd RExp RExp
 | RGre RExp RExp
 | RDiv RExp RExp
 | RElem BasicType
  deriving (Eq,Ord,Show)

data StmtVar =
   RVarBlock [BlockVar]
  deriving (Eq,Ord,Show)

data BlockVar =
   RBlockVar Iden Type RExp
  deriving (Eq,Ord,Show)

data Boolean =
   RTrue
 | RFalse
  deriving (Eq,Ord,Show)

data Type =
   RTypeInt
 | RTypeFloat
 | RTypeChar
 | RTypeString
 | RTypeBool
 | TypeVoid
  deriving (Eq,Ord,Show)

