module Absbool where

-- Haskell module generated by the BNF converter


data Program =
   Prog Boolean
  deriving (Eq,Ord,Show)

data Boolean =
   BTrue
 | BFalse
  deriving (Eq,Ord,Show)

data Type =
   TypeInt
 | TypeFloat
 | TypeChar
 | TypeString
 | TypeBool
  deriving (Eq,Ord,Show)

